security:
  oauth2:
    client:
      clientId: driver
      clientSecret: 1234
      accessTokenUri: http://localhost:8762/api/uaa/oauth/token
      grant-type: client_credentials
      scope: server

server:
  servlet:
    context-path: /driver
  port: 8006

feign:
  hystrix:
    enabled: true


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vytra
    username: postgres
    password: d3v3l0p3r
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
